USE DATABASE SOC;
USE SCHEMA PUBLIC;

CREATE TABLE R_ROOM IF NOT EXISTS(
    ROOM_NUM INTEGER NOT NULL PRIMARY KEY,
    ROOM_NAME VARCHAR(20) NOT NULL,
    FLOR_NUM BYTEINT,
    BULD_NAME VARCHAR(20),
    ROOM_TYP VARCHAR(10),
    ROOM_DAY_RATE SMALLINT NOT NULL,
    CRTN_DT DATE NOT NULL,
    EXEC_ID INTEGER NOT NULL
);

CREATE TABLE R_PART IF NOT EXISTS(
    PART_ID INTEGER NOT NULL PRIMARY KEY,
    SRC_ID INTEGER NOT NULL,
    SRC_TYP VARCHAR(50) NOT NULL
);

CREATE TABLE R_MEDC IF NOT EXISTS(
    MEDC_ID INTEGER NOT NULL PRIMARY KEY,
    MEDC_CD VARCHAR(10) NOT NULL,
    MEDC_NAME VARCHAR(250),
    MEDC_COND VARCHAR(100),
    MEDC_CATG VARCHAR(100) NOT NULL,
    MANF_BRND VARCHAR(100) NOT NULL,
    EXEC_ID INTEGER NOT NULL
);

CREATE TABLE O_INDV IF NOT EXISTS(
    PART_ID INTEGER NOT NULL PRIMARY KEY,
    INDV_NAME VARCHAR(100) NOT NULL,
    INDV_FIRS_NAME VARCHAR(100) NOT NULL,
    INDV_STTS_CD VARCHAR(10) NOT NULL,
    CRTN_DTTM TIMESTAMP(0) NOT NULL,
    UPDT_DTTM TIMESTAMP(0) NOT NULL,
    BIRT_DT DATE,
    BIRT_CITY VARCHAR(100),
    BIRT_CNTR VARCHAR(100),
    SOCL_NUM VARCHAR(15),
    EXEC_ID INTEGER NOT NULL
);

CREATE TABLE O_STFF IF NOT EXISTS(
    PART_ID INTEGER PRIMARY KEY,
    WORK_STRT_DTTM TIMESTAMP(0) NOT NULL,
    WORK_END_DTTM TIMESTAMP(0),
    WORK_END_RESN TIMESTAMP(0),
    EXEC_ID INTEGER NOT NULL
);

CREATE TABLE O_ADDR IF NOT EXISTS(
    PART_ID INTEGER,
    STRT_VALD_DTTM TIMESTAMP(0),
    STRT_NUM VARCHAR(10) NOT NULL,
    STRT_DSC VARCHAR(250) NOT NULL,
    COMP_STRT VARCHAR(250),
    POST_CD VARCHAR(10) NOT NULL,
    CITY_NAME VARCHAR(100),
    CNTR_NAME VARCHAR(100),
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL,
    PRIMARY KEY (PART_ID, STRT_VALD_DTTM)
);

CREATE TABLE O_TELP IF NOT EXISTS(
    PART_ID INTEGER,
    STRT_VALD_DTTM TIMESTAMP(0),
    CNTR_IND VARCHAR(5),
    TELP_NUM VARCHAR(20) NOT NULL,
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL,
    PRIMARY KEY (PART_ID, STRT_VALD_DTTM)
);

CREATE TABLE O_CONS IF NOT EXISTS(
    CONS_ID INTEGER PRIMARY KEY,
    STFF_ID INTEGER NOT NULL,
    PATN_ID INTEGER NOT NULL,
    CONS_STRT_DTTM TIMESTAMP(0) NOT NULL,
    CONS_END_DTTM TIMESTAMP(0) NOT NULL,
    PATN_WEGH INTEGER NOT NULL,
    PATN_TEMP INTEGER,
    TEMP_UNIT VARCHAR(15),
    BLD_PRSS INTEGER,
    PATH_DSC VARCHAR(250),
    DIBT_IND BYTEINT,
    TRET_ID INTEGER,
    HOSP_IND INTEGER,
    EXEC_ID INTEGER NOT NULL,
    FOREIGN KEY (STFF_ID) REFERENCES R_PART(PART_ID),
    FOREIGN KEY (PATN_ID) REFERENCES R_PART(PART_ID)
);

CREATE TABLE O_HOSP IF NOT EXISTS (
    HOSP_ID INTEGER PRIMARY KEY,
    CONS_ID INTEGER NOT NULL,
    ROOM_NUM SMALLINT NOT NULL,
    HOSP_STRT_DTTM TIMESTAMP(0) NOT NULL,
    HOSP_END_DTTM TIMESTAMP(0) NOT NULL,
    HOSP_FINL_RATE TIMESTAMP(0) NOT NULL,
    STFF_ID INTEGER NOT NULL,
    EXEC_ID INTEGER NOT NULL,
    FOREIGN KEY (STFF_ID) REFERENCES R_PART (PART_ID),
    FOREIGN KEY (CONS_ID) REFERENCES O_CONS (CONS_ID)
);

CREATE TABLE O_TRET IF NOT EXISTS(
    TRET_ID INTEGER NOT NULL PRIMARY KEY,
    MEDC_ID INTEGER,
    MEDC_QTY SMALLINT,
    DOSG_DSC VARCHAR(100) NOT NULL,
    CONS_ID INTEGER NOT NULL,
    TRET_CRTN_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL,
    FOREIGN KEY (CONS_ID) REFERENCES O_CONS (CONS_ID),
    FOREIGN KEY (MEDC_ID) REFERENCES R_MEDC (MEDC_ID)
);