INSERT INTO WRK.PUBLIC.R_ROOM (ROOM_NUM, ROOM_NAME, FLOR_NUM, BULD_NAME, ROOM_TYP, ROOM_DAY_RATE, CRTN_DT, EXEC_ID)
SELECT NO_CHAMBRE, NOM_CHAMBRE, NO_ETAGE, NOM_BATIMENT, TYPE_CHAMBRE, PRIX_JOUR, DT_CREATION, NULL
FROM WRK.PUBLIC.CHAMBRE;

INSERT INTO WRK.PUBLIC.O_TRET (TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM, EXEC_ID)
SELECT t.ID_TRAITEMENT, m.MEDC_ID, t.QTE_MEDICAMENT, t.DSC_POSOLOGIE, t.ID_CONSULT, t.TS_CREATION_TRAITEMENT, NULL
FROM WRK.PUBLIC.TRAITEMENT t
JOIN WRK.PUBLIC.R_MEDC m
  ON t.CD_MEDICAMENT = m.MEDC_CD
 AND t.CATG_MEDICAMENT = m.MEDC_CATG
 AND t.MARQUE_FABRI = m.MANF_BRND;

INSERT INTO WRK.PUBLIC.R_PART (PART_ID, SRC_ID, SRC_TYP)
SELECT DISTINCT 
  ROW_NUMBER() OVER (ORDER BY ID_PERSONNEL, FONCTION_PERSONNEL) + (SELECT COALESCE(MAX(PART_ID),0) FROM WRK.PUBLIC.R_PART) AS PART_ID,
  ID_PERSONNEL, FONCTION_PERSONNEL
FROM WRK.PUBLIC.PERSONNEL;

INSERT INTO WRK.PUBLIC.R_PART (PART_ID, SRC_ID, SRC_TYP)
SELECT DISTINCT 
  ROW_NUMBER() OVER (ORDER BY ID_PATIENT) + (SELECT COALESCE(MAX(PART_ID),0) FROM WRK.PUBLIC.R_PART) AS PART_ID,
  ID_PATIENT, 'Patient'
FROM WRK.PUBLIC.PATIENT;

INSERT INTO WRK.PUBLIC.O_INDV (PART_ID, INDV_NAME, INDV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM, UPDT_DTTM, EXEC_ID)
SELECT p.PART_ID, w.NOM_PERSONNEL, w.PRENOM_PERSONNEL, w.CD_STATUT_PERSONNEL, w.TS_CREATION_PERSONNEL, w.TS_MAJ_PERSONNEL, NULL
FROM WRK.PUBLIC.PERSONNEL w
JOIN WRK.PUBLIC.R_PART p ON w.ID_PERSONNEL = p.SRC_ID AND w.FONCTION_PERSONNEL = p.SRC_TYP;

INSERT INTO WRK.PUBLIC.O_INDV (PART_ID, INDV_NAME, INDV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM, UPDT_DTTM, BIRT_DT, BIRT_CITY, BIRT_CNTR, SOCL_NUM, EXEC_ID)
SELECT p.PART_ID, w.NOM_PATIENT, w.PRENOM_PATIENT, 'Actif', w.TS_CREATION_PATIENT, w.TS_MAJ_PATIENT, w.DT_NAISS, w.VILLE_NAISS, w.PAYS_NAISS, w.NUM_SECU, NULL
FROM WRK.PUBLIC.PATIENT w
JOIN WRK.PUBLIC.R_PART p ON w.ID_PATIENT = p.SRC_ID AND p.SRC_TYP = 'Patient';

INSERT INTO WRK.PUBLIC.O_STFF (PART_ID, WORK_STRT_DTTM, WORK_END_DTTM, WORK_END_RESN, EXEC_ID)
SELECT p.PART_ID, w.TS_DEBUT_ACTIVITE, w.TS_FIN_ACTIVITE, w.RAISON_FIN_ACTIVITE, NULL
FROM WRK.PUBLIC.PERSONNEL w
JOIN WRK.PUBLIC.R_PART p ON w.ID_PERSONNEL = p.SRC_ID AND w.FONCTION_PERSONNEL = p.SRC_TYP;

INSERT INTO WRK.PUBLIC.O_TELP (PART_ID, CNTR_IND, TELP_NUM, STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID)
SELECT p.PART_ID, w.IND_PAYS_NUM_TELP, w.NUM_TELEPHONE, w.TS_CREATION_PATIENT, w.TS_MAJ_PATIENT, NULL
FROM WRK.PUBLIC.PATIENT w
JOIN WRK.PUBLIC.R_PART p ON w.ID_PATIENT = p.SRC_ID AND p.SRC_TYP = 'Patient';

INSERT INTO WRK.PUBLIC.O_ADDR (PART_ID, STRT_NUM, STRT_DSC, COMP_STRT, POST_CD, CITY_NAME, CNTR_NAME, STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID)
SELECT p.PART_ID, w.NUM_VOIE, w.DSC_VOIE, w.CMPL_VOIE, w.CD_POSTAL, w.VILLE, w.PAYS, w.TS_CREATION_PATIENT, w.TS_MAJ_PATIENT, NULL
FROM WRK.PUBLIC.PATIENT w
JOIN WRK.PUBLIC.R_PART p ON w.ID_PATIENT = p.SRC_ID AND p.SRC_TYP = 'Patient';
 
INSERT INTO WRK.PUBLIC.O_CONS (CONS_ID, STFF_ID, PATN_ID, CONS_STRT_DTTM, CONS_END_DTTM, PATN_WEGH, PATN_TEMP, TEMP_UNIT, BLD_PRSS, PATH_DSC, DIBT_IND, TRET_ID, HOSP_IND, EXEC_ID)
SELECT c.ID_CONSULT,
  stff.PART_ID AS STFF_ID,
  patn.PART_ID AS PATN_ID,
  c.TS_DEBUT_CONSULT, c.TS_FIN_CONSULT, c.POIDS_PATIENT, c.TEMP_PATIENT, c.UNIT_TEMP, c.TENSION_PATIENT, c.DSC_PATHO,
  CASE WHEN c.INDIC_DIABETE = 'True' THEN 1 ELSE 0 END AS DIBT_IND,
  c.ID_TRAITEMENT,
  CASE WHEN c.INDIC_HOSPI = 'True' THEN 1 ELSE 0 END AS HOSP_IND,
  NULL
FROM WRK.PUBLIC.CONSULTATION c
JOIN WRK.PUBLIC.R_PART stff ON c.ID_PERSONNEL = stff.SRC_ID AND stff.SRC_TYP <> 'Patient'
JOIN WRK.PUBLIC.R_PART patn ON c.ID_PATIENT = patn.SRC_ID AND patn.SRC_TYP = 'Patient';
 
INSERT INTO WRK.PUBLIC.O_HOSP (HOSP_ID, CONS_ID, ROOM_NUM, HOSP_STRT_DTTM, HOSP_END_DTTM, HOSP_FINL_RATE, STFF_ID, EXEC_ID)
SELECT h.ID_HOSPI, h.ID_CONSULT, h.NO_CHAMBRE, h.TS_DEBUT_HOSPI, h.TS_FIN_HOSPI, h.COUT_HOSPI, p.PART_ID, NULL
FROM WRK.PUBLIC.HOSPITALISATION h
JOIN WRK.PUBLIC.R_PART p ON h.ID_PERSONNEL_RESP = p.SRC_ID AND p.SRC_TYP <> 'Patient';

INSERT INTO WRK.PUBLIC.R_MEDC (MEDC_ID, MEDC_CD, MEDC_NAME, MEDC_COND, MEDC_CATG, MANF_BRND, EXEC_ID)
SELECT DISTINCT 
  ROW_NUMBER() OVER (ORDER BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI) + (SELECT COALESCE(MAX(MEDC_ID),0) FROM WRK.PUBLIC.R_MEDC) AS MEDC_ID,
  CD_MEDICAMENT, NOM_MEDICAMENT, CONDIT_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI, NULL
FROM WRK.PUBLIC.MEDICAMENT;