DELETE * FROM SOC.public.R_ROOM;
INSERT INTO SOC.public.R_ROOM
SELECT *
FROM WRK.public.R_ROOM wrk;

DELETE * FROM SOC.public.R_PART;
INSERT INTO SOC.public.R_PART
SELECT *
FROM WRK.public.R_PART;

DELETE * FROM SOC.public.R_MEDC;
INSERT INTO SOC.public.R_MEDC
SELECT *
FROM WRK.public.R_MEDC wrk;


INSERT INTO SOC.public.O_INDV
SELECT *
FROM WRK.public.O_INDV wrk;

INSERT INTO SOC.public.O_STFF
SELECT *
FROM WRK.public.O_STFF wrk;

INSERT INTO SOC.public.O_ADDR
SELECT *
FROM WRK.public.O_ADDR wrk;

INSERT INTO SOC.public.O_TELP
SELECT *
FROM WRK.public.O_TELP wrk;

INSERT INTO SOC.public.O_CONS
SELECT *
FROM WRK.public.O_CONS wrk;

INSERT INTO SOC.public.O_HOSP
SELECT *
FROM WRK.public.O_HOSP wrk;

INSERT INTO SOC.public.O_TRET
SELECT *
FROM WRK.public.O_TRET wrk;