
-- Remplissage de O_TRET avec le MEDC_ID récupéré depuis R_MEDC via jointure sur TRAITEMENT
INSERT INTO O_TRET (TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM, EXEC_ID)
SELECT 
    t.ID_TRAITEMENT AS TRET_ID,
    m.MEDC_ID,
    t.QTE_MEDICAMENT AS MEDC_QTY,
    t.DSC_POSOLOGIE AS DOSG_DSC,
    t.ID_CONSULT AS CONS_ID,
    t.TS_CREATION_TRAITEMENT AS TRET_CRTN_DTTM,
    NULL AS EXEC_ID -- À adapter si tu as une logique pour EXEC_ID
FROM TRAITEMENT t
JOIN R_MEDC m
  ON t.CD_MEDICAMENT = m.MEDC_CD
 AND t.CATG_MEDICAMENT = m.MEDC_CATG
 AND t.MARQUE_FABRI = m.MANF_BRND;