USE DATABASE STG;

USE SCHEMA public;

CREATE OR REPLACE PROCEDURE insert_chambre(
  NO_CHAMBRE INTEGER,
  NOM_CHAMBRE VARCHAR,
  NO_ETAGE BYTEINT,
  NOM_BATIMENT VARCHAR,
  TYPE_CHAMBRE VARCHAR,
  PRIX_JOUR SMALLINT,
  DT_CREATION DATE
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO CHAMBRE VALUES (:NO_CHAMBRE, :NOM_CHAMBRE, :NO_ETAGE, :NOM_BATIMENT, :TYPE_CHAMBRE, :PRIX_JOUR, :DT_CREATION);
  RETURN 'CHAMBRE insérée';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_traitement(
  ID_TRAITEMENT INTEGER,
  CD_MEDICAMENT INTEGER,
  CATG_MEDICAMENT VARCHAR,
  MARQUE_FABRI VARCHAR,
  QTE_MEDICAMENT SMALLINT,
  DSC_POSOLOGIE VARCHAR,
  ID_CONSULT INTEGER,
  TS_CREATION_TRAITEMENT TIMESTAMP
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO TRAITEMENT VALUES (:ID_TRAITEMENT, :CD_MEDICAMENT, :CATG_MEDICAMENT, :MARQUE_FABRI, :QTE_MEDICAMENT, :DSC_POSOLOGIE, :ID_CONSULT, :TS_CREATION_TRAITEMENT);
  RETURN 'TRAITEMENT inséré';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_personnel(
  ID_PERSONNEL INTEGER,
  NOM_PERSONNEL VARCHAR,
  PRENOM_PERSONNEL VARCHAR,
  FONCTION_PERSONNEL VARCHAR,
  TS_DEBUT_ACTIVITE TIMESTAMP,
  TS_FIN_ACTIVITE TIMESTAMP,
  RAISON_FIN_ACTIVITE VARCHAR,
  TS_CREATION_PERSONNEL TIMESTAMP,
  TS_MAJ_PERSONNEL TIMESTAMP,
  CD_STATUT_PERSONNEL VARCHAR
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO PERSONNEL VALUES (:ID_PERSONNEL, :NOM_PERSONNEL, :PRENOM_PERSONNEL, :FONCTION_PERSONNEL, :TS_DEBUT_ACTIVITE, :TS_FIN_ACTIVITE, :RAISON_FIN_ACTIVITE, :TS_CREATION_PERSONNEL, :TS_MAJ_PERSONNEL, :CD_STATUT_PERSONNEL);
  RETURN 'PERSONNEL inséré';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_patient(
  ID_PATIENT INTEGER,
  NOM_PATIENT VARCHAR,
  PRENOM_PATIENT VARCHAR,
  DT_NAISS DATE,
  VILLE_NAISS VARCHAR,
  PAYS_NAISS VARCHAR,
  NUM_SECU VARCHAR,
  IND_PAYS_NUM_TELP VARCHAR,
  NUM_TELEPHONE VARCHAR,
  NUM_VOIE VARCHAR,
  DSC_VOIE VARCHAR,
  CMPL_VOIE VARCHAR,
  CD_POSTAL VARCHAR,
  VILLE VARCHAR,
  PAYS VARCHAR,
  TS_CREATION_PATIENT TIMESTAMP,
  TS_MAJ_PATIENT TIMESTAMP
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO PATIENT VALUES (:ID_PATIENT, :NOM_PATIENT, :PRENOM_PATIENT, :DT_NAISS, :VILLE_NAISS, :PAYS_NAISS, :NUM_SECU, :IND_PAYS_NUM_TELP, :NUM_TELEPHONE, :NUM_VOIE, :DSC_VOIE, :CMPL_VOIE, :CD_POSTAL, :VILLE, :PAYS, :TS_CREATION_PATIENT, :TS_MAJ_PATIENT);
  RETURN 'PATIENT inséré';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_consultation(
  ID_CONSULT INTEGER,
  ID_PERSONNEL INTEGER,
  ID_PATIENT INTEGER,
  TS_DEBUT_CONSULT TIMESTAMP,
  TS_FIN_CONSULT TIMESTAMP,
  POIDS_PATIENT INTEGER,
  TEMP_PATIENT INTEGER,
  UNIT_TEMP VARCHAR,
  TENSION_PATIENT INTEGER,
  DSC_PATHO VARCHAR,
  INDIC_DIABETE VARCHAR,
  ID_TRAITEMENT INTEGER,
  INDIC_HOSPI VARCHAR
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO CONSULTATION VALUES (:ID_CONSULT, :ID_PERSONNEL, :ID_PATIENT, :TS_DEBUT_CONSULT, :TS_FIN_CONSULT, :POIDS_PATIENT, :TEMP_PATIENT, :UNIT_TEMP, :TENSION_PATIENT, :DSC_PATHO, :INDIC_DIABETE, :ID_TRAITEMENT, :INDIC_HOSPI);
  RETURN 'CONSULTATION insérée';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_hospitalisation(
  ID_HOSPI INTEGER,
  ID_CONSULT INTEGER,
  NO_CHAMBRE SMALLINT,
  TS_DEBUT_HOSPI TIMESTAMP,
  TS_FIN_HOSPI TIMESTAMP,
  COUT_HOSPI TIMESTAMP,
  ID_PERSONNEL_RESP INTEGER
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO HOSPITALISATION VALUES (:ID_HOSPI, :ID_CONSULT, :NO_CHAMBRE, :TS_DEBUT_HOSPI, :TS_FIN_HOSPI, :COUT_HOSPI, :ID_PERSONNEL_RESP);
  RETURN 'HOSPITALISATION insérée';
END;
$$;

CREATE OR REPLACE PROCEDURE insert_medicament(
  CD_MEDICAMENT VARCHAR,
  NOM_MEDICAMENT VARCHAR,
  CONDIT_MEDICAMENT VARCHAR,
  CATG_MEDICAMENT VARCHAR,
  MARQUE_FABRI VARCHAR
)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO MEDICAMENT VALUES (:CD_MEDICAMENT, :NOM_MEDICAMENT, :CONDIT_MEDICAMENT, :CATG_MEDICAMENT, :MARQUE_FABRI);
  RETURN 'MEDICAMENT inséré';
END;
$$;

