INSERT INTO SOC.public.R_ROOM
SELECT *
FROM WRK.public.R_ROOM;

INSERT INTO SOC.public.R_PART
SELECT *
FROM WRK.public.R_PART;

INSERT INTO SOC.public.R_MEDC
SELECT *
FROM WRK.public.R_MEDC;

INSERT INTO SOC.public.O_INDV
SELECT *
FROM WRK.public.O_INDV;

INSERT INTO SOC.public.O_STFF
SELECT *
FROM WRK.public.O_STFF;

INSERT INTO SOC.public.O_ADDR
SELECT *
FROM WRK.public.O_ADDR;

INSERT INTO SOC.public.O_TELP
SELECT *
FROM WRK.public.O_TELP;

INSERT INTO SOC.public.O_CONS
SELECT *
FROM WRK.public.O_CONS;

INSERT INTO SOC.public.O_HOSP
SELECT *
FROM WRK.public.O_HOSP;

INSERT INTO SOC.public.O_TRET
SELECT *
FROM WRK.public.O_TRET;