--USE DATABASE STG;

--USE SCHEMA public;

CREATE OR REPLACE PROCEDURE INSERT_CHAMBRE(
  NO_CHAMBRE_ARRAY ARRAY,
  NOM_CHAMBRE_ARRAY ARRAY,
  NO_ETAGE_ARRAY ARRAY,
  NOM_BATIMENT_ARRAY ARRAY,
  TYPE_CHAMBRE_ARRAY ARRAY,
  PRIX_JOUR_ARRAY ARRAY,
  DT_CREATION_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:NO_CHAMBRE_ARRAY);
  
  INSERT INTO STG.PUBLIC.CHAMBRE
  SELECT 
    :NO_CHAMBRE_ARRAY[SEQ4()]::INTEGER,
    :NOM_CHAMBRE_ARRAY[SEQ4()]::VARCHAR,
    :NO_ETAGE_ARRAY[SEQ4()]::BYTEINT,
    :NOM_BATIMENT_ARRAY[SEQ4()]::VARCHAR,
    :TYPE_CHAMBRE_ARRAY[SEQ4()]::VARCHAR,
    :PRIX_JOUR_ARRAY[SEQ4()]::SMALLINT,
    :DT_CREATION_ARRAY[SEQ4()]::DATE
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' CHAMBRE(S) insérée(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_TRAITEMENT(
  ID_TRAITEMENT_ARRAY ARRAY,
  CD_MEDICAMENT_ARRAY ARRAY,
  CATG_MEDICAMENT_ARRAY ARRAY,
  MARQUE_FABRI_ARRAY ARRAY,
  QTE_MEDICAMENT_ARRAY ARRAY,
  DSC_POSOLOGIE_ARRAY ARRAY,
  ID_CONSULT_ARRAY ARRAY,
  TS_CREATION_TRAITEMENT_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:ID_TRAITEMENT_ARRAY);
  
  INSERT INTO STG.PUBLIC.TRAITEMENT
  SELECT 
    :ID_TRAITEMENT_ARRAY[SEQ4()]::INTEGER,
    :CD_MEDICAMENT_ARRAY[SEQ4()]::INTEGER,
    :CATG_MEDICAMENT_ARRAY[SEQ4()]::VARCHAR,
    :MARQUE_FABRI_ARRAY[SEQ4()]::VARCHAR,
    :QTE_MEDICAMENT_ARRAY[SEQ4()]::SMALLINT,
    :DSC_POSOLOGIE_ARRAY[SEQ4()]::VARCHAR,
    :ID_CONSULT_ARRAY[SEQ4()]::INTEGER,    
    CASE 
      WHEN :TS_CREATION_TRAITEMENT_ARRAY[SEQ4()] IS NULL OR :TS_CREATION_TRAITEMENT_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_CREATION_TRAITEMENT_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END  
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' TRAITEMENT(S) inséré(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_PERSONNEL(
  ID_PERSONNEL_ARRAY ARRAY,
  NOM_PERSONNEL_ARRAY ARRAY,
  PRENOM_PERSONNEL_ARRAY ARRAY,
  FONCTION_PERSONNEL_ARRAY ARRAY,
  TS_DEBUT_ACTIVITE_ARRAY ARRAY,
  TS_FIN_ACTIVITE_ARRAY ARRAY,
  RAISON_FIN_ACTIVITE_ARRAY ARRAY,
  TS_CREATION_PERSONNEL_ARRAY ARRAY,
  TS_MAJ_PERSONNEL_ARRAY ARRAY,
  CD_STATUT_PERSONNEL_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:ID_PERSONNEL_ARRAY);
  
  INSERT INTO STG.PUBLIC.PERSONNEL
  SELECT    :ID_PERSONNEL_ARRAY[SEQ4()]::INTEGER,
    :NOM_PERSONNEL_ARRAY[SEQ4()]::VARCHAR,
    :PRENOM_PERSONNEL_ARRAY[SEQ4()]::VARCHAR,
    :FONCTION_PERSONNEL_ARRAY[SEQ4()]::VARCHAR,    
    CASE 
      WHEN :TS_DEBUT_ACTIVITE_ARRAY[SEQ4()] IS NULL OR :TS_DEBUT_ACTIVITE_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_DEBUT_ACTIVITE_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    CASE 
      WHEN :TS_FIN_ACTIVITE_ARRAY[SEQ4()] IS NULL OR :TS_FIN_ACTIVITE_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_FIN_ACTIVITE_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    :RAISON_FIN_ACTIVITE_ARRAY[SEQ4()]::VARCHAR,
    CASE 
      WHEN :TS_CREATION_PERSONNEL_ARRAY[SEQ4()] IS NULL OR :TS_CREATION_PERSONNEL_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(TO_DATE(REPLACE(:TS_CREATION_PERSONNEL_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD'))
    END AS TS_CREATION_PERSONNEL,
    CASE 
      WHEN :TS_MAJ_PERSONNEL_ARRAY[SEQ4()] IS NULL OR :TS_MAJ_PERSONNEL_ARRAY[SEQ4()] = ''  THEN TS_CREATION_PERSONNEL
      ELSE TO_TIMESTAMP(REPLACE(:TS_MAJ_PERSONNEL_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    :CD_STATUT_PERSONNEL_ARRAY[SEQ4()]::VARCHAR  
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' PERSONNEL(S) inséré(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_PATIENT(
  ID_PATIENT_ARRAY ARRAY,
  NOM_PATIENT_ARRAY ARRAY,
  PRENOM_PATIENT_ARRAY ARRAY,
  DT_NAISS_ARRAY ARRAY,
  VILLE_NAISS_ARRAY ARRAY,
  PAYS_NAISS_ARRAY ARRAY,
  NUM_SECU_ARRAY ARRAY,
  IND_PAYS_NUM_TELP_ARRAY ARRAY,
  NUM_TELEPHONE_ARRAY ARRAY,
  NUM_VOIE_ARRAY ARRAY,
  DSC_VOIE_ARRAY ARRAY,
  CMPL_VOIE_ARRAY ARRAY,
  CD_POSTAL_ARRAY ARRAY,
  VILLE_ARRAY ARRAY,
  PAYS_ARRAY ARRAY,
  TS_CREATION_PATIENT_ARRAY ARRAY,
  TS_MAJ_PATIENT_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:ID_PATIENT_ARRAY);
  
  INSERT INTO STG.PUBLIC.PATIENT
  SELECT 
    :ID_PATIENT_ARRAY[SEQ4()]::INTEGER,
    :NOM_PATIENT_ARRAY[SEQ4()]::VARCHAR,
    :PRENOM_PATIENT_ARRAY[SEQ4()]::VARCHAR,
    :DT_NAISS_ARRAY[SEQ4()]::DATE,
    :VILLE_NAISS_ARRAY[SEQ4()]::VARCHAR,
    :PAYS_NAISS_ARRAY[SEQ4()]::VARCHAR,
    :NUM_SECU_ARRAY[SEQ4()]::VARCHAR,
    :IND_PAYS_NUM_TELP_ARRAY[SEQ4()]::VARCHAR,
    :NUM_TELEPHONE_ARRAY[SEQ4()]::VARCHAR,
    :NUM_VOIE_ARRAY[SEQ4()]::VARCHAR,
    :DSC_VOIE_ARRAY[SEQ4()]::VARCHAR,
    :CMPL_VOIE_ARRAY[SEQ4()]::VARCHAR,
    :CD_POSTAL_ARRAY[SEQ4()]::VARCHAR,    
    :VILLE_ARRAY[SEQ4()]::VARCHAR,    
    :PAYS_ARRAY[SEQ4()]::VARCHAR,    
    CASE 
      WHEN :TS_CREATION_PATIENT_ARRAY[SEQ4()] IS NULL OR :TS_CREATION_PATIENT_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_CREATION_PATIENT_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    CASE 
      WHEN :TS_MAJ_PATIENT_ARRAY[SEQ4()] IS NULL OR :TS_MAJ_PATIENT_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_MAJ_PATIENT_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END  
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' PATIENT(S) inséré(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_CONSULTATION(
  ID_CONSULT_ARRAY ARRAY,
  ID_PERSONNEL_ARRAY ARRAY,
  ID_PATIENT_ARRAY ARRAY,
  TS_DEBUT_CONSULT_ARRAY ARRAY,
  TS_FIN_CONSULT_ARRAY ARRAY,
  POIDS_PATIENT_ARRAY ARRAY,
  TEMP_PATIENT_ARRAY ARRAY,
  UNIT_TEMP_ARRAY ARRAY,
  TENSION_PATIENT_ARRAY ARRAY,
  DSC_PATHO_ARRAY ARRAY,
  INDIC_DIABETE_ARRAY ARRAY,
  ID_TRAITEMENT_ARRAY ARRAY,
  INDIC_HOSPI_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:ID_CONSULT_ARRAY);
    INSERT INTO STG.PUBLIC.CONSULTATION
  SELECT 
    :ID_CONSULT_ARRAY[SEQ4()]::INTEGER,
    :ID_PERSONNEL_ARRAY[SEQ4()]::INTEGER,    
    :ID_PATIENT_ARRAY[SEQ4()]::INTEGER,    
    CASE 
      WHEN :TS_DEBUT_CONSULT_ARRAY[SEQ4()] IS NULL OR :TS_DEBUT_CONSULT_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_DEBUT_CONSULT_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    CASE 
      WHEN :TS_FIN_CONSULT_ARRAY[SEQ4()] IS NULL OR :TS_FIN_CONSULT_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_FIN_CONSULT_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    :POIDS_PATIENT_ARRAY[SEQ4()]::INTEGER,
    :TEMP_PATIENT_ARRAY[SEQ4()]::INTEGER,
    :UNIT_TEMP_ARRAY[SEQ4()]::VARCHAR,
    :TENSION_PATIENT_ARRAY[SEQ4()]::INTEGER,
    :DSC_PATHO_ARRAY[SEQ4()]::VARCHAR,
    :INDIC_DIABETE_ARRAY[SEQ4()]::VARCHAR,
    :ID_TRAITEMENT_ARRAY[SEQ4()]::INTEGER,
    :INDIC_HOSPI_ARRAY[SEQ4()]::VARCHAR  
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' CONSULTATION(S) insérée(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_HOSPITALISATION(
  ID_HOSPI_ARRAY ARRAY,
  ID_CONSULT_ARRAY ARRAY,
  NO_CHAMBRE_ARRAY ARRAY,
  TS_DEBUT_HOSPI_ARRAY ARRAY,
  TS_FIN_HOSPI_ARRAY ARRAY,
  COUT_HOSPI_ARRAY ARRAY,
  ID_PERSONNEL_RESP_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:ID_HOSPI_ARRAY);
    INSERT INTO STG.PUBLIC.HOSPITALISATION
  SELECT 
    :ID_HOSPI_ARRAY[SEQ4()]::INTEGER,
    :ID_CONSULT_ARRAY[SEQ4()]::INTEGER,
    :NO_CHAMBRE_ARRAY[SEQ4()]::SMALLINT,    
    CASE 
      WHEN :TS_DEBUT_HOSPI_ARRAY[SEQ4()] IS NULL OR :TS_DEBUT_HOSPI_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_DEBUT_HOSPI_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    CASE 
      WHEN :TS_FIN_HOSPI_ARRAY[SEQ4()] IS NULL OR :TS_FIN_HOSPI_ARRAY[SEQ4()] = '' THEN NULL
      ELSE TO_TIMESTAMP(REPLACE(:TS_FIN_HOSPI_ARRAY[SEQ4()]::VARCHAR, '#', '0'), 'YYYY-MM-DD-HH24-MI-SS')
    END,
    :COUT_HOSPI_ARRAY[SEQ4()]::FLOAT,
    :ID_PERSONNEL_RESP_ARRAY[SEQ4()]::INTEGER  
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' HOSPITALISATION(S) insérée(s)';
END;
$$;

CREATE OR REPLACE PROCEDURE INSERT_MEDICAMENT(
  CD_MEDICAMENT_ARRAY ARRAY,
  NOM_MEDICAMENT_ARRAY ARRAY,
  CONDIT_MEDICAMENT_ARRAY ARRAY,
  CATG_MEDICAMENT_ARRAY ARRAY,
  MARQUE_FABRI_ARRAY ARRAY
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  rows_count INTEGER;
BEGIN
  rows_count := ARRAY_SIZE(:CD_MEDICAMENT_ARRAY);
  
  INSERT INTO STG.PUBLIC.MEDICAMENT
  SELECT 
    :CD_MEDICAMENT_ARRAY[SEQ4()]::VARCHAR,
    :NOM_MEDICAMENT_ARRAY[SEQ4()]::VARCHAR,
    :CONDIT_MEDICAMENT_ARRAY[SEQ4()]::VARCHAR,
    :CATG_MEDICAMENT_ARRAY[SEQ4()]::VARCHAR,
    :MARQUE_FABRI_ARRAY[SEQ4()]::VARCHAR
  FROM TABLE(GENERATOR(ROWCOUNT => :rows_count));
  
  RETURN :rows_count || ' MEDICAMENT(S) inséré(s)';
END;
$$;

