INSERT INTO WRK.PUBLIC.CHAMBRE SELECT * FROM STG.PUBLIC.CHAMBRE;
INSERT INTO WRK.PUBLIC.TRAITEMENT SELECT * FROM STG.PUBLIC.TRAITEMENT;
INSERT INTO WRK.PUBLIC.PERSONNEL SELECT * FROM STG.PUBLIC.PERSONNEL;
INSERT INTO WRK.PUBLIC.PATIENT SELECT * FROM STG.PUBLIC.PATIENT;
INSERT INTO WRK.PUBLIC.CONSULTATION SELECT * FROM STG.PUBLIC.CONSULTATION;
INSERT INTO WRK.PUBLIC.HOSPITALISATION SELECT * FROM STG.PUBLIC.HOSPITALISATION;
INSERT INTO WRK.PUBLIC.MEDICAMENT SELECT * FROM STG.PUBLIC.MEDICAMENT;